# Generated by Django 2.2.16 on 2022-02-20 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20220220_1320'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='user_author',
        ),
    ]
