<!--Запросы на получения списка ресурсов-->
###
#  запрос на получение списка постов
GET http://127.0.0.1:8000/api/v1/posts/
###
#  запрос на получение списка групп
GET http://127.0.0.1:8000/api/v1/groups/
###
#  запрос на получение списка комментариев
GET http://127.0.0.1:8000/api/v1/posts/109/comments/
###


<!--Запросы на получение ресурса по id-->
###
#  запрос на получение поста
GET http://127.0.0.1:8000/api/v1/posts/78/
###
#  запрос на получение группы
GET http://127.0.0.1:8000/api/v1/groups/3/
###
#  запрос на получение комментария
GET http://127.0.0.1:8000/api/v1/posts/109/comments/26/
